<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_05_ChangePassword</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f6550438-4c6f-4630-8cbe-164998545160</testSuiteGuid>
   <testCaseLink>
      <guid>d1f79fe2-ea57-4625-944a-f204f1863cf2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Requirement_02/data-driven/TC_05_Changepassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d40f8fb1-e5f0-4ff6-bc84-1ddb2786a28f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/changePasswordWithCSV</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d40f8fb1-e5f0-4ff6-bc84-1ddb2786a28f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>﻿password</value>
         <variableId>88ceb3f0-7e85-4dce-ba4e-5313b54eb97b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d40f8fb1-e5f0-4ff6-bc84-1ddb2786a28f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>new_password</value>
         <variableId>362251dd-cf6a-42da-b042-4d38fca19056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d40f8fb1-e5f0-4ff6-bc84-1ddb2786a28f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirm_password</value>
         <variableId>b557a021-5005-46fc-8aed-7cd593c19725</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
