<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>internal-data</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>013c9779-1a4b-4e6c-8272-3e9a69fb2481</testSuiteGuid>
   <testCaseLink>
      <guid>fa8d0ed8-6a85-4dee-8181-3aa2c574b66d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login/test 1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e22b6704-5c13-41de-a467-96d546eca0aa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login/internal-data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e22b6704-5c13-41de-a467-96d546eca0aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8583f516-5a48-46dd-acd1-b381fa5c1247</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e22b6704-5c13-41de-a467-96d546eca0aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>cb1c0429-13a6-4d91-8f14-9a9793e1c454</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
